### ISSUE TITLE
Error while loading world.. "An item with the same key has already been added."

### ISSUE THREAD

**Issue by ghost** [NiclasOlofsson/MiNET#257]
I don't know what would cause MiNET to put an item in an array with the same key, but I get this error while loading a world (no plugins). I don't think the world is corrupt, pocketmine, and minecraft java edition load it fine (it is a anvil world, mca files)

Happens when I join the server.

```
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at fNbt.NbtCompound.ReadTag(NbtBinaryReader readStream)
   at fNbt.NbtList.ReadTag(NbtBinaryReader readStream)
   at fNbt.NbtCompound.ReadTag(NbtBinaryReader readStream)
   at fNbt.NbtCompound.ReadTag(NbtBinaryReader readStream)
   at fNbt.NbtFile.LoadFromStreamInternal(Stream stream, TagSelector tagSelector)
   at fNbt.NbtFile.LoadFromStream(Stream stream, NbtCompression compression, TagSelector selector)
   at fNbt.NbtFile.LoadFromStream(Stream stream, NbtCompression compression)
   at MiNET.Worlds.AnvilWorldProvider.GetChunk(ChunkCoordinates coordinates, String basePath, IWorldGenerator generator)
   at MiNET.Worlds.AnvilWorldProvider.<GenerateChunkColumn>b__41_0(ChunkCoordinates coordinates)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at MiNET.Worlds.AnvilWorldProvider.GenerateChunkColumn(ChunkCoordinates chunkCoordinates)
   at MiNET.Worlds.Level.<GenerateChunks>d__169.MoveNext()
```

**Comment by NiclasOlofsson** [comment]
It is a public map that I can test myself?

**Comment by madecode15** [comment]
https://www.dropbox.com/s/xv6e5hfo2p4e2iv/lobby.zip?dl=0

The map is breeze island; however, I used mcedit to take the map and paste it into another world (via schematic).

So the chunks in this world came from an mcedit schematic of breeze island.

Reproducing steps:
1) Add the world to MiNET
2) Turn on MiNET
2) The error will appear in console

**Comment by NiclasOlofsson** [comment]
it is having issues with 2 chunks. 20,1 and 17,-1. If i disable these chunks it loads the map (but with 2 missing chunks). I suspect it's the tile-entities on these chunks that aren't working properly.  Did you add content to the chests in these chunks?

**Comment by NiclasOlofsson** [comment]
Removing the empty chests (2) in these chunks solves the problem. Looks like fNBT doesn't really like empty compound tags.

**Comment by madecode15** [comment]
Huh, strange issue... this is problematic because many SG maps have empty chests, and in the plugin I am writing I refill chests on the fly when a user taps a chest.

Surprised no one has reported such a issue before 🤔

**Comment by NiclasOlofsson** [comment]
Sure they can be empty, most maps have empty chests for MiNET. Most do full them runtime too. Just that on that specific map, (only) 2 of the chests have NBT that doesn't seem to fit the format entirely. There where lots of chests on that map that works fine.

**Comment by NiclasOlofsson** [comment]
@fragmer Would you mind having a look at this NBT issue?
