### ISSUE TITLE
Can't join server in Linux

### ISSUE THREAD

**Issue by Potatoshare88** [NiclasOlofsson/MiNET#406]
ERROR [?] - Parsing login
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.MemoryStream.InternalReadInt32()
   at System.IO.BinaryReader.ReadInt32()
   at fNbt.NbtBinaryReader.ReadInt32()
   at MiNET.LoginMessageHandler.DecodeCert(McpeLogin message) in /home/ubuntu/mc/pe/MiNET/src/MiNET/MiNET/LoginMessageHandler.cs:line 114

(Error Message)

I saw [here](https://github.com/NiclasOlofsson/MiNET/wiki/Getting-Started) and compiled MiNET. But I can't Join Server.

+ I am not good at English.

**Comment by NiclasOlofsson** [comment]
Use the right version of the client. The right version is displayed in the server browser.
