### ISSUE TITLE
Can't load world

### ISSUE THREAD

**Issue by FloGamerMC** [NiclasOlofsson/MiNET#603]
I created a world an add it in the server config an this exeptions came up 
`System.IO.InvalidDataException: Could not auto-detect compression format.
   at fNbt.NbtFile.DetectCompression(Stream stream)
   at fNbt.NbtFile.LoadFromStream(Stream stream, NbtCompression compression, TagSelector selector)
   at fNbt.NbtFile.LoadFromFile(String fileName, NbtCompression compression, TagSelector selector)
   at fNbt.NbtFile.LoadFromFile(String fileName)
   at MiNET.Worlds.AnvilWorldProvider.Initialize() in C:\Daten\Coding\Projekte\MiNET\src\MiNET\MiNET\Worlds\AnvilWorldProvider.cs:line 239
   at MiNET.Worlds.Level.Initialize() in C:\Daten\Coding\Projekte\MiNET\src\MiNET\MiNET\Worlds\Level.cs:line 139
   at MiNET.LevelManager.GetLevel(Player player, String name) in C:\Daten\Coding\Projekte\MiNET\src\MiNET\MiNET\LevelManager.cs:line 115
   at MiNET.MiNetServer.StartServer() in C:\Daten\Coding\Projekte\MiNET\src\MiNET\MiNET\MiNetServer.cs:line 154
`

**Comment by kennyvv** [comment]
The current anvil provider implementation is outdated & only supports up to 1.11 worlds. See issue #604.
